### ISSUE TITLE
video playing in the recents

### ISSUE THREAD

**Issue by Tarch1** [jeffshee/gnome-ext-hanabi#10]
Hi,
as well as wallpaper the video is playing in a window in the recents
https://imgur.com/a/6mnECUy

**Comment by S1rPh0en1x** [comment]
You may be using the Wayland window manager instead of the X11 window manager.
For me the same Issue ocurs if I use Wayland as window manager.
You can confirm this by looking at "gnome settings - about".

**Comment by Tarch1** [comment]
yeah it is, but there is a workaround?

**Comment by jeffshee** [comment]
@Tarch1 @S1rPh0en1x Thanks for reporting~
This extension is designed to work with both X11 and Wayland in mind. So this is definitely a bug.

**Comment by jeffshee** [comment]
Fixed! It was just a careless mistake (*ﾉω・*)ﾃﾍ

![Screenshot from 2022-08-09 18-53-37](https://user-images.githubusercontent.com/25530920/183622015-e3b0866f-a7ce-42f1-bd9e-476806162b55.png)
