### ISSUE TITLE
what do i do? Arch Gnome

### ISSUE THREAD

**Issue by BALVEY7** [jeffshee/gnome-ext-hanabi#118]
hi I've installed the version 45 but my gnome is version 46 now and new version came out
so what is that i need to do? do i rm it or do i git clone again or build it again?
not sure what to do this is as for help 
Thank you

**Comment by jeffshee** [comment]
Hi @BALVEY7 
Inside the directory that you had git cloned previously, 
```
git pull
./run.sh install
```
Then logout and login again.
