### ISSUE TITLE
Arch Gnome no video working

### ISSUE THREAD

**Issue by BALVEY7** [jeffshee/gnome-ext-hanabi#119]
**Description**
in short video doesn't play all i get is black screen, miusic plays but again no video

**OS and Shell Information**
Arch GNOME X11 6.623-1 LTS
 - OS: Arch
 - GNOME Shell: [46]
 - Session type: [ X11]

**Steps to Reproduce**
Please provide the steps to reproduce the bug you are encountering.
1. Go to "extensions, turn the extension on and black screen"
2. Click on "...".
3. See error.

**Expected Behavior**
video play in the background

**Actual Behavior**
Black screen with music

**Additional Information**
Please provide any additional information that you think might be helpful, such as error messages, screenshots, screen recordings, or links.

**Comment by BALVEY7** [comment]
issue fixed turns out it was missing a package gst-libav
simply 
`sudo pacman -Syyu`

`sudo pacman -S gst-libav`

`reboot`

issue has been fixed, also I do recommend that you play .webm format first, if the video plays than this should be the solution for you, if it doesn't... are you sure you using .webm not .webp? if so you will probably need to install uhhhmmm ah yeah just do the top command and it should work.
That's all folks bye bye

**Comment by Dazawassa** [comment]
Attempted the fix provided and did not work on Fedora. Fedora doesn't have the relevant packages for the fix so I installed pacman and installed the packages through that instead. After a reboot the backgrounds were still black.

**Comment by BALVEY7** [comment]
... Why did you installed pacman? 
Pacman is for Arch and arch distro only!

Have you even played the video in Webm format? 

This was only an idea what needs to be done the rest you kinda had to look it up and find it for yourself of what packages are used for arch and what are used for fedora
