### ISSUE TITLE
Auto Pause on Window Focus or Maximize

### ISSUE THREAD

**Issue by RizkyFauziIlmi** [jeffshee/gnome-ext-hanabi#121]
**Description**
Auto Pause on Window Focus or Maximize

**OS and Shell Information**
 - OS: Ubuntu 23.10 x86_64
 - GNOME Shell: GNOME 45.2
 - Session type: Wayland

**Additional Information**
Auto Pause on Window Focus or Maximize, it's more convenient if you can choose when will it pause or play, and it will be better if can be set in extension setting and menubar

**Comment by jeffshee** [comment]
Hi @RizkyFauziIlmi, it's coming soon!

Please check the `auto-pause` branch if you want to test it now, or wait for a few more weeks for it to get polished and merged to the `master`~

**Comment by RizkyFauziIlmi** [comment]
My fault I didn't see that branch, okay I'll try it
