### ISSUE TITLE
gif wallpaper freezes at the end of it

### ISSUE THREAD

**Issue by orcbolg3612** [jeffshee/gnome-ext-hanabi#137]
**Description**
gif wallpaper freezes at the the end of it. 
**OS and Shell Information**
 - OS: Fedora 40
 - GNOME Shell: 46.2
 - Session type: Wayland

https://github.com/jeffshee/gnome-ext-hanabi/assets/154581201/b3f67825-452e-4fee-943a-956e8962b85d

**Comment by orcbolg3612** [comment]
I'm also installed clapper

**Comment by jeffshee** [comment]
Hi @orcbolg3612 Thanks for reporting!
Please do note that GIF wallpaper is not tested, thus not supported at the moment.
