### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Renen12** [jeffshee/gnome-ext-hanabi#138]
The video being played is just a black screen =(
I'm running arch Linux and Gnome 46 on Wayland.

**Steps to Reproduce**
The steps to reproduce the issue is just to use the extension on my hardware/software combination, I don't have any useful details, sorry.

**Expected Behavior**
The extension to, uhhhhh, do what it's supposed to do?

**Additional Information**
I'm using an intel arc a750, the drivers should probably be included in the kernel, mesa installed, gstreamer also installed.

https://github.com/jeffshee/gnome-ext-hanabi/assets/112264908/e2a2f001-f00e-4658-be5a-cd2317157f51

The audio of the video is kinda messed up in the recording, but it sounds normal outside of recordings.

**Comment by JoaoLucasGdS** [comment]
Also having the same issue.

**Comment by thibault-napoleon** [comment]
Same issue here. Have you found a solution?
