### ISSUE TITLE
extension can't turn on

### ISSUE THREAD

**Issue by junior25hacker** [jeffshee/gnome-ext-hanabi#141]
The settings of extension hanabi-extension@jeffshee.github.io had an error:
```
SyntaxError: import declarations may only appear at top level of a module @ resource:///org/gnome/Shell/Extensions/js/misc/extensionUtils.js:4:0

Stack trace:
  @file:///home/junior/.local/share/gnome-shell/extensions/hanabi-extension@jeffshee.github.io/prefs.js:23:24
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
```

**Comment by jeffshee** [comment]
Hi, you are probably using the wrong branch. 
> Clone the repo
> - For GNOME 45 and later
> ```git clone https://github.com/jeffshee/gnome-ext-hanabi.git```
> - For GNOME 44 and earlier
> ```git clone https://github.com/jeffshee/gnome-ext-hanabi.git -b legacy```
