### ISSUE TITLE
Weird Corners On Video / corners not rounded.

### ISSUE THREAD

**Issue by CodedIsTaken** [jeffshee/gnome-ext-hanabi#148]
The Corner Seems To Be "Damaged" On Gnome 46.

 - OS: Fedora 40.
 - GNOME Shell: GNOME 46
 - Session type: Wayland
 - 
**Steps to Reproduce**
Please provide the steps to reproduce the bug you are encountering.
I Just Uploaded The Video and it occured

i expected the corners to be either rounded or squared.

but one of the corners was rounded then went to square
![Uploading Screenshot from 2024-09-22 17-20-37.png…]()

**Comment by CodedIsTaken** [comment]
sorry, image missing.
![Screenshot from 2024-09-22 17-20-37](https://github.com/user-attachments/assets/824d3b43-ed0f-4864-8375-88f2e7098a9f)

**Comment by AngelSherry** [comment]
Yes, I can also reappear the issue by using gesture. You can see the rounded corners in the upper left corner are gradually deteriorating.
![螢幕快照 2024-09-23 15-50-00](https://github.com/user-attachments/assets/e67e8424-3f80-4b58-ab70-8dfcf995ad0b)
![螢幕快照 2024-09-23 15-50-13](https://github.com/user-attachments/assets/667bc1b8-4db2-4cfa-b2cf-8650dae71992)
![螢幕快照 2024-09-23 15-50-24](https://github.com/user-attachments/assets/6dd554b2-119e-41c3-b21b-04d82fe26b4c)

**Comment by jeffshee** [comment]
Thanks for reporting, I can confirm this issue too, and will try to fix it soon!
