### ISSUE TITLE
Integration for Blur My Shell does not work on the dock sometimes

### ISSUE THREAD

**Issue by Xarth-Mai** [jeffshee/gnome-ext-hanabi#150]
**Description**  
There is an issue with the integration of Blur My Shell on the dock when using the Hanabi extension.

**OS and Shell Information**  
- OS: [ArchLinux]  
- Kernel: [Linux 6.11.1-arch1-1]  
- GNOME Shell: [47.0]  
- Hanabi: [[gnome-47_d8dae32](https://github.com/jeffshee/gnome-ext-hanabi/tree/d8dae327b604920fa68e09e6783297453131b364)]
- Session Type: [Wayland]  

**Steps to Reproduce**  
1. Enable the Hanabi extension and Blur My Shell extension  
2. Restart GNOME Shell  
3. Observe the blur effect on the dock

**Expected Behavior**  
Blur My Shell should display the blur effect correctly on the dock and handle dynamic blur according to the video wallpaper.

**Actual Behavior**  
The blur effect works properly on the apps page, but it doesn't work on the dock.
After manually changing the wallpaper once, the blur effect on the dock temporarily works, but it breaks again after restarting GNOME.

**Additional Information**
![image](https://github.com/user-attachments/assets/74247cf3-2b41-4e0c-aeaa-296f265e450a)

**Comment by jeffshee** [comment]
Hi @Xarth-Mai, thanks for reporting!
I can also confirm this issue on my system (Gnome 46, Manjaro). However, I believe it's an issue of Blur My Shell, as **it also happens without Hanabi Extension.**

Dock doesn't blur even Dash to Dock blur is enabled
![image](https://github.com/user-attachments/assets/f5e33d2d-9811-43f6-976d-b4c7e6a14c11)

Perhaps you should open an issue on Blur My Shell instead. 😃

**Comment by Xarth-Mai** [comment]
> Hi @Xarth-Mai, thanks for reporting!
> 
> I can also confirm this issue on my system (Gnome 46, Manjaro). However, I believe it's an issue of Blur My Shell, as **it also happens without Hanabi Extension.**
> 
> 
> 
> Dock doesn't blur even Dash to Dock blur is enabled
> 
> ![image](https://github.com/user-attachments/assets/f5e33d2d-9811-43f6-976d-b4c7e6a14c11)
> 
> 
> 
> Perhaps you should open an issue on Blur My Shell instead. 😃

It's a little different. In my screenshot, the dock is blurred, but the blurred background is the original wallpaper, not my video wallpaper.

**Comment by Xarth-Mai** [comment]
[The code here](https://github.com/jeffshee/gnome-ext-hanabi/commit/132beb9e0c7c9180d955340c150dc79d804936e6#diff-f30a4cdaf5e159863ceb53b78c5f9738f8618d9d955b754eb7b66fe42ae74151R67) seems to not work properly on GNOME 47. I tried running it in the console, but nothing happened.

**Comment by Xarth-Mai** [comment]
Sorry, I made a mistake, this is actually a compatibility issue with dash-to-dock@micxgx.gmail.com

**Comment by jeffshee** [comment]
@Xarth-Mai Never mind, feel free to report if you find any other bugs 😄
