### ISSUE TITLE
Ghost Windows When using with Blur My Shell

### ISSUE THREAD

**Issue by yofukashino** [jeffshee/gnome-ext-hanabi#153]
**Description**
An Image on a Window That can take the foreground space upon click appears which I can not interact with or close with. By Clicking in the dock to open/unminimize the application now I can interact with it. But it was minimized and shouldn't be shown.
Video Attached Below.

**OS and Shell Information**
 - OS: Fedora 40
 - GNOME Shell: 46
 - Session type: X11
 
**Steps to Reproduce**
Please provide the steps to reproduce the bug you are encountering.
1. Open Bunch of Applications. 
2. Minimise them all with key bind to minimise all apps. 
3. Press Super to get all apps/workspace menu
4. Select an App 
5. Ghost windows of other apps appear in the background

**Expected Behavior**
Window Should stay minimised and not show its window while being minimised

**Actual Behavior**
The window is minimized but a ghost window that cant be interacted with appears.

**Additional Information**
https://youtu.be/BsvLmTgQdb8

**Comment by jeffshee** [comment]
Hi @yofukashino, thanks for reporting!
Could you please explain how you made that key binding to minimize all apps?
Did you key bind to a custom command, or you are using a predefined one in settings?

I tried the predefined one in settings as following, and the bug shown in your video doesn't happen on my system:
![image](https://github.com/user-attachments/assets/889f2e05-b4f8-4a85-a628-283d0f4062aa)

I tested with Gnome Shell 46 and x11 session as well.

**Comment by AngelSherry** [comment]
> Hi @yofukashino, thanks for reporting! Could you please explain how you made that key binding to minimize all apps? Did you key bind to a custom command, or you are using a predefined one in settings?
> 
> I tried the predefined one in settings as following, and the bug shown in your video doesn't happen on my system: ![image](https://private-user-images.githubusercontent.com/25530920/373864636-889f2e05-b4f8-4a85-a628-283d0f4062aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNTc0NzAsIm5iZiI6MTcyODE1NzE3MCwicGF0aCI6Ii8yNTUzMDkyMC8zNzM4NjQ2MzYtODg5ZjJlMDUtYjRmOC00YTg1LWE2MjgtMjgzZDBmNDA2MmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDE5MzkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNmE3YjIxZmZhZDkwMGEwMDY0MWUzNDExZjQ3M2Y3NTYyNWRkOTNiM2NkY2VjYzcxNGI4ZjlkNzdmZDI2NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GWEXhrKiFL3O8iGYtd8W77qVA0du5X0ZBtlvcZ-B7Rg)
> 
> I tested with Gnome Shell 46 and x11 session as well.

I know how to reproduce the issue. It does use "Hide all normal window". With enabling "Pause on Maximize or Fullscreen" on gnome-ext-hanabi,

![image](https://github.com/user-attachments/assets/592e976e-4fe9-4e3d-9b8f-1ac170136dd8)

 when there is no any maximized window, this shortcut works as expect and the video will continue playing. But if **there is any maximized or fullscreen window**, the video will be paused even using the shortcut to "Hide all normal window".

There is the video about how to reproduce the issue.

https://github.com/user-attachments/assets/a522c520-0e47-4d30-b1c9-b9f4374b1502

**Comment by jeffshee** [comment]
@AngelSherry Thanks!
From what I see, I believe that yours is a different issue from what @yofukashino is reporting.
Yours is probably easy to fix, as I can reproduce the issue on my system, also I roughly know how to fix it~ 😉

**Comment by yofukashino** [comment]
> @AngelSherry Thanks! From what I see, I believe that yours is a different issue from what @yofukashino is reporting. Yours is probably easy to fix, as I can reproduce the issue on my system, also I roughly know how to fix it~ 😉

I am us

> Hi @yofukashino, thanks for reporting! Could you please explain how you made that key binding to minimize all apps? Did you key bind to a custom command, or you are using a predefined one in settings?
> 
> I tried the predefined one in settings as following, and the bug shown in your video doesn't happen on my system: ![image](https://private-user-images.githubusercontent.com/25530920/373864636-889f2e05-b4f8-4a85-a628-283d0f4062aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNzEzOTksIm5iZiI6MTcyODI3MTA5OSwicGF0aCI6Ii8yNTUzMDkyMC8zNzM4NjQ2MzYtODg5ZjJlMDUtYjRmOC00YTg1LWE2MjgtMjgzZDBmNDA2MmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDAzMTgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllZDNhOTQ4ZmJjZTk4YjEwNzdkYWU1MTljZTU1M2Q5NDM1Njk0M2E5YjZhOTJhOWFjZDIzYjQ2NWE3Njk2OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pPIr6DukSW-PjuwCfE2OVLqXslbew0jNaYzhYB05LM0)
> 
> I tested with Gnome Shell 46 and x11 session as well.

Okay let me clear myself, it's not about how you minimise it happens even if i had minimised them manually.

For me the steps to reproduce are:
Requirements: 
- Blur my shell and Hanabi, Hidamari must not be running (it prevents the issue from happening somehow)
- Blur my shell must have application blur on with blur on overview on aswell. 
Steps: 
1. Open applications
2. minimise them with keybind or manually
3. open the workspace overview  and open the app (NOT ALT TAB, must be from workspace overview)
4. ghost window are behind it

**Comment by jeffshee** [comment]
Hi @yofukashino, thanks for providing the details. 🙂

After further investigation, it was a bug of Blur my Shell, not Hanabi.
The bug you described also happened without Hanabi installed.
I will close this issue and direct you to the Blur my Shell instead: https://github.com/aunetx/blur-my-shell/issues/664

**Comment by yofukashino** [comment]
> Hi @yofukashino, thanks for providing the details. 🙂
> 
> After further investigation, it was a bug of Blur my Shell, not Hanabi. The bug you described also happened without Hanabi installed. I will close this issue and direct you to the Blur my Shell instead: [aunetx/blur-my-shell#664](https://github.com/aunetx/blur-my-shell/issues/664)

okay, thanks. weirdly, having Hidamari running prevents the bug.
