### ISSUE TITLE
Black Screen, no image, sound works

### ISSUE THREAD

**Issue by brunoorsolon** [jeffshee/gnome-ext-hanabi#154]
**Description**
No image, but sound works

**OS and Shell Information**
Please provide your OS name and version, GNOME Shell version, and the session type (X11/Wayland).
 - OS: Ubuntu 24.04.1 LTS
 - GNOME Shell: 46
 - Session type: Wayland

**Steps to Reproduce**
Please provide the steps to reproduce the bug you are encountering.
1. Enable Hanabi.

**Expected Behavior**
Video playing as live wallpaper

**Actual Behavior**
Black screen. If I unmute the video, I can hear the sound, so it must be loading "something".

**Comment by jeffshee** [comment]
Hi @brunoorsolon, thanks for reporting.

This sounds like a Gtk4 media backend or multimedia codecs issue to me.
Please make sure that you have these installed:
```bash
# Multimedia codecs, etc.
sudo apt install ubuntu-restricted-extras

# GTK4 media backend
sudo apt install libgtk-4-media-gstreamer

# GstPlay and GstAudio
sudo apt install gir1.2-gst-plugins-base-1.0 gir1.2-gst-plugins-bad-1.0
```

**Comment by brunoorsolon** [comment]
Unfortunately, I do have all that installed and still no image. I use an AMD video card, not sure if thats an issue

I am temporarily using VLC media as a live wallpaper source since Hanabi didnt work

**Comment by raymonable** [comment]
I'm having the same issue. I have an NVIDIA gpu and AMD integrated graphics. The image is black but I can hear audio.

I tried just using an image and it works just fine (albeit, in the center of the image with no clear way to adjust its position).

Additionally, I have 2 16:9 displays and one 21:9 and the video does not conform to the size of the 21:9 display even with "Cover" enabled in the settings. The wallpaper underneath is still visible. (If this should be made into a new issue, please let me know.)

**Comment by raymonable** [comment]
Correction about the last comment:
![image](https://github.com/user-attachments/assets/7590c46e-60c4-4e4d-99cd-facc9d070924)

(The display on the left is the 21:9 display and other is 16:9, they are on the wrong displays for some reason. But still black, no video and only sound is playing

**Comment by raymonable** [comment]
This is still an issue for me.

**Comment by jeffshee** [comment]
@raymonable 

> Additionally, I have 2 16:9 displays and one 21:9 and the video does not conform to the size of the 21:9 display even with "Cover" enabled in the settings. The wallpaper underneath is still visible.

The last commit doesn't fix this just yet (also I think this is a different, multi monitor specific issue). But the playback should work now. 
Please let me know if it doesn't.

**Comment by raymonable** [comment]
It does not fix the issues with video playback.
I have reinstalled the extension using the gnome-47 branch and it still shows the black screens.

I am on Arch Linux, and I have checked that all of the libraries you shown above are installed.
