### ISSUE TITLE
[update requests] Gnome 43

### ISSUE THREAD

**Issue by Tuxino88** [jeffshee/gnome-ext-hanabi#23]
On gnome 43 video covers topbar

**Comment by Tuxino88** [comment]
Hey Jeff , with latest commit problem remain 🫤

[Video del 2022-11-25 11-25-35.webm](https://user-images.githubusercontent.com/75674245/203963188-8e8fa601-c1b8-4f7b-a48d-7c696e3274c1.webm)

**Comment by jeffshee** [comment]
@Tuxino88 Thanks!
Reported at #25 as well.

**Comment by jeffshee** [comment]
Hi @Tuxino88 

It is fixed in the latest commit! Sorry for the late and Merry Christmas~ 🎅
