### ISSUE TITLE
Support Gnome 43

### ISSUE THREAD

**Issue by delucca** [jeffshee/gnome-ext-hanabi#24]
I can't activate the extension, it says that it is incompatible with my Gnome version

**Comment by delucca** [comment]
> Hi @delucca , If you were just upgraded your GNOME from 42, please try reinstalling the extension. Then you should be able to activate the extension after restarting the shell.
> 
> Please tell me if that doesn't work. =)

hi

actually, I never used Hanabi extension. I was using Gnome 43 already when I first installed it

I've completely removed the extension, installed again, restarted my computer but still:
![](https://i.imgur.com/KDTYi16.png)

**Comment by delucca** [comment]
I can use Hidamari (without the GNOME extension) but when I install Hanabi I can´t activate the extension itself

**Comment by Seikm** [comment]
can't use the extension in gnome 43 either.
