### ISSUE TITLE
[Bug] Render video window over the upper bar of gnome shell and some other extensions

### ISSUE THREAD

**Issue by hax0r31337** [jeffshee/gnome-ext-hanabi#26]
This extension renders the video window over the top bar of gnome shell,  
and some extensions like [DING](https://extensions.gnome.org/extension/2087/desktop-icons-ng-ding/), and make [Dash to Dock](https://extensions.gnome.org/extension/307/dash-to-dock/) glitches.   
The dock bar from the Dash to Dock extension is blinking
![image](https://user-images.githubusercontent.com/65506006/206363858-721fa564-a642-483b-b506-df0fd3cdebef.png)

**Comment by jeffshee** [comment]
Hi @hax0r31337 ,

It is fixed and so far I have no issues with DING and Dash to Dock extension from my testing. Please try the latest master~
