### ISSUE TITLE
Option to disable sound

### ISSUE THREAD

**Issue by Tarch1** [jeffshee/gnome-ext-hanabi#3]
First of all thanks for your works!
Works great on Arch, as I said in the title the sound is great in some videos but for other it's better to have an option to disable it.
During the compilation compilation I had the same error message as in #2 : 
meson.build:50: WARNING: The variable(s) 'settings_schema' in the input file 'metadata.json.in' are not present in the given configuration data
but nonetheless works.

**Comment by jeffshee** [comment]
Hi @Tarch1,
The functionality is there and the option will be added in the future.
If you like tinkering with code, you can try editing the `extension.js` :
```js
function launchRenderer() {
    data.reloadTime = 100;
    let argv = [];
    argv.push(GLib.build_filenamev([ExtensionUtils.getCurrentExtension().path, 'renderer.js']));
    // The path. Allows the program to find translations, settings and modules.
    argv.push('-P');
    argv.push(ExtensionUtils.getCurrentExtension().path);
    // The video path.
    argv.push('-F');
    argv.push(videoPath);
    argv.push('-M'); // <-- Add this line to mute
```
Don't forget to rerun the installation script and reload the shell after modifying the code.

**Comment by Tarch1** [comment]
Thanks I'll give it a try

**Comment by Tarch1** [comment]
Yeah it works thanks

**Comment by jeffshee** [comment]
This is already in the latest master. Closed as completed~
