### ISSUE TITLE
suggestion add option preserve rounded corners in overview workspace

### ISSUE THREAD

**Issue by EtereosDawn** [jeffshee/gnome-ext-hanabi#34]
hello! the extension works well it is only necessary to turn it off and on for the video to work. the workspaces with spikes give me a touch. I wish there was an option that would preserve them even if it cuts the video at the corners of the video. I like the design of gnome and it made me curious if it's possible to preserve the workspace's rounded edges. in extension. I think it would be an interesting feature. and i use fedora 37

[Gravação de tela de 2023-01-07 05-36-11.webm](https://user-images.githubusercontent.com/34200212/211141820-ad507f8d-823f-4e76-a077-36432ba9048c.webm)

and how hide gsj?
![image](https://user-images.githubusercontent.com/34200212/211141863-0be86dae-1dbe-4c89-9a6a-d13f2ef3da08.png)

**Comment by jeffshee** [comment]
Hi @EtereosDawn, thanks for reporting.

>it's possible to preserve the workspace's rounded edges

Yeah, I'm aware of this issue, and I'm currently doing some research. It has a low priority, so it may take some time.

>and how hide gsj?

Done =)

**Comment by AlynxZhou** [comment]
> Hi @EtereosDawn, thanks for reporting.
> 
> > it's possible to preserve the workspace's rounded edges
> 
> Yeah, I'm aware of this issue, and I'm currently doing some research. It has a low priority, so it may take some time.
> 

At least I have a working branch and I will submit it once I cleaned code and added comments:

![image](https://user-images.githubusercontent.com/8444615/217704392-caff9c13-b298-4f8c-8022-b9e6c06acf7d.png)

**Comment by alex285** [comment]
does rounded corners work on 45?

**Comment by jeffshee** [comment]
@alex285 seem borked but I don't know why
