### ISSUE TITLE
Wallpaper doesnt fit correctly on my display (Arch linux on 16:10 display)

### ISSUE THREAD

**Issue by Quark04** [jeffshee/gnome-ext-hanabi#37]
[Screencast from 2023-02-03 23-41-08.webm](https://user-images.githubusercontent.com/109768663/216581588-886fb6c1-47ab-4816-b1c8-26211ce44958.webm)

**Comment by Seikm** [comment]
Just out of curiosity, can you use a wallpaper with a 16:10 resolution (1920 x 1200), and try again?
Just want to know if this would work lol

You can quickly convert your wallpaper into another dimension for testing using ffmpeg.
`ffmpeg -i (input video with extension) -vf scale=-1920:1200 (output video with extension)`

**Comment by Schneegans** [comment]
> You can quickly convert your wallpaper into another dimension for testing using ffmpeg.
> `ffmpeg -i (input video with extension) -vf scale=-1920:1200 (output video with extension)`

For me, this did not properly rescale the video. This worked for me: `ffmpeg -i (input video with extension) -aspect 1920:1200 -c copy (output video with extension)`. And then the video nicely fills the entire screen.

**Comment by Quark04** [comment]
Yep this worked thanks!!!

**Comment by Rafostar** [comment]
What is the desired outcome here? Stretch video to fill screen? Crop center to fill screen? Or maybe even an option for both?

For the first one, you should be able to just set `clappersink.force_aspect_ratio = false`. But I am considering replacing this property eventually to add more options for scaling/cropping in the future.

**Comment by jeffshee** [comment]
Based on GNOME's wallpaper setting, we could have these modes as an option:
![hanabi-design_01](https://user-images.githubusercontent.com/25530920/219023325-0f2ddc01-8d59-44fd-bef9-69931c49b2b4.png)

However, there will still be problems for users who have a multi-monitor setup with different aspect ratios, if we do the scaling on the renderer side. (issue #30) So, we should play the video at its native resolution (the window size should be equal to the video resolution) and the scaling should be done on the extension side.

@Rafostar Do you know how to get the video resolution from GStreamer so we can set the renderer window size to it?

**Comment by jeffshee** [comment]
We still need some optimization, but here is the current progress~ 😎

![ezgif com-optimize](https://user-images.githubusercontent.com/25530920/220134065-e097eb57-7729-4333-b1b9-46a2fd3e6df8.gif)
