### ISSUE TITLE
Stop the live wallpaper when specific applications is running

### ISSUE THREAD

**Issue by sekalengrengginang** [jeffshee/gnome-ext-hanabi#39]
When specific apps like Steam is running the live wallpaper is stop/paused for better performance in-game.

**Comment by jeffshee** [comment]
Hi @sekalengrengginang, thanks for the feature request!

>When specific apps like Steam is running the live wallpaper is stop/paused for better performance in-game.

While this is technically possible, Linux does not have a real definition of "app", so it requires further consideration.
The GNOME definition of an app refers to a program that provides a "*.desktop" file that appears in the application menu.
However, some programs do not provide `*.desktop`. For example, most of the Steam games...

> live wallpaper can be disabled/paused when using a fullscreen application

Yep, this feature is planned. 😎
As the first step, a simple toggle that allows users to play/pause the wallpaper will be added to the top bar.
Then we will work on window detection stuff so that it can pause the wallpaper if there is any fullscreen/maximized window.

**Comment by 3laws** [comment]
> However, some programs do not provide *.desktop. For example, most of the Steam games...

This can be circumvented by checking if `steam`  itself is running, as well as `wine` and `lutris`. No need to actually check for apps. The new background portal from GNOME may also come in handy for this purpose, as well as implementing it by itself in the project.

**Comment by yucellmustafa** [comment]
I wrote a small control command. I also assigned it to the hotkey. it's working for now.

*xprop must be installed.

```bash
if xprop -id $(xprop -root | awk '/_NET_ACTIVE_WINDOW\(WINDOW\)/{print $NF}') | grep -q "_NET_WM_STATE_FULLSCREEN"; then
	/usr/bin/gnome-extensions disable hanabi-extension@jeffshee.github.io
else
	/usr/bin/gnome-extensions enable hanabi-extension@jeffshee.github.io
fi
```

**Comment by Cherro59** [comment]
> To add to this, maybe the live wallpaper can be disabled/paused when using a fullscreen application (like wallpaper engine provides a toggle to do this), this can maybe save battery life when using this on battery as well.

I made my custom impemetation on this with python/dbus. There is a problem how to know is there any app opened in fullscreen. So I used [this](https://github.com/hseliger/window-calls-extended) to know is there any app in focus and maximized. It's not native but works well.


`
import json
import dbus
import dbus.mainloop.glib
import time
from gi.repository import GLib
import subprocess
import re
value = 0 # this is ID of hanabi renderer in dbus
result = ' '
s = ''
is_there_fulscreen = False
def init():
    global value
    args = ["dbus-send", "--session", "--print-reply", "--dest=org.freedesktop.DBus", "/org/freedesktop/DBus", "org.freedesktop.DBus.GetNameOwner", "string:io.github.jeffshee.HanabiRenderer"]

    result = subprocess.run(args, stdout=subprocess.PIPE)

    output = result.stdout.decode('utf-8')
    match = re.search(r'string\s+":(\d+\.\d+)"', output)
    value = match.group(1)


time.sleep(5) # time to wait before wallpaper will appear
dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
bus = dbus.SessionBus()
def getinfo():
    global s 
    args = [
    'gdbus',
    'call',
    '--session',
    '--dest',
    'org.gnome.Shell',
    '--object-path',
    '/org/gnome/Shell/Extensions/WindowsExt',
    '--method',
    'org.gnome.Shell.Extensions.WindowsExt.List'
    ]

    result = subprocess.run(args, capture_output=True)
    
    output = result.stdout.decode('utf-8') #parcing WindowsExt output
    s = output[2:-4]
    

def send_message():
    init()
    if is_there_fulscreen == True:
        
        args = ["dbus-send", "--type=method_call", f"--dest=:{value}", "/io/github/jeffshee/HanabiRenderer", "io.github.jeffshee.HanabiRenderer.setPause"]
        # send over dbus command to pause
        subprocess.run(args)
     
    else:
        
        args = ["dbus-send", "--type=method_call", f"--dest=:{value}", "/io/github/jeffshee/HanabiRenderer", "io.github.jeffshee.HanabiRenderer.setPlay"]
        # send over dbus command to play
        subprocess.run(args)
      

#  infinity loop
while True:
    getinfo() # getting info about nahabi via dbus
    data = json.loads(s) # convert command output to json

    for d in data: # parsing if there maximized and focused app
        if d.get("maximized") == 3 and d.get("focus") == True:
            is_there_fulscreen = True
            
            break
        else:
            is_there_fulscreen = False
        
        
    # call send_message() 
    send_message()

    # little stop to now waste much resoures of cpu
    time.sleep(0.5)
`

**Comment by Cherro59** [comment]
I made my custom script with python/dbus. Main problem is to know is there any maximized and focused app so I used [this](https://github.com/hseliger/window-calls-extended) to know it( it will be needed if you want to use my script, just install the extension). There is script: 
[fullscreen.txt](https://github.com/jeffshee/gnome-ext-hanabi/files/11242134/fullscreen.txt)

**Comment by ThomasHineXYZ** [comment]
This feature would also be great for laptop users.
