### ISSUE TITLE
Right click menu

### ISSUE THREAD

**Issue by Tarch1** [jeffshee/gnome-ext-hanabi#4]
Hello,
I noticed that using this extension causes a very slow display of the context menu, disabling it returns to normal

**Comment by jeffshee** [comment]
Hi @Tarch1,
Thanks for reporting. While I don't observe any slowdown with my system (desktop), playing a video constantly in the background can have some impact on system performance. I believe some optimizations will be needed in the future.

**Comment by Tarch1** [comment]
First of all, I apologize for the little information provided.

CPU: i5-8300H
GPU: nvidia 1050 (driver: nvidia nvidia-utils)
RAM: 16 GB
OS: Arch
DE: Gnome 42
