### ISSUE TITLE
Translatable this extension

### ISSUE THREAD

**Issue by mjkim0727** [jeffshee/gnome-ext-hanabi#46]
Could you translatable this extension?

I'll translate Preferences texts into Korean.

**Comment by jeffshee** [comment]
Hi @mjkim0727, sorry to keep you waiting.

This is my first time to make translatable project, so I have to spend time learning for how to do that. 😅
To translate the extension, you can start with the pot file located at `src/po`. 
When making translation, please use `src/po/hanabi-extension@jeffshee.github.io.pot` as the template. 
Also, you can check my Japanese translation (`src/po/ja.po`) as an example.

Thanks in advance for your contribution! Feel free to ask me any question~

**Comment by jeffshee** [comment]
Closed as the extension is translatable now.
