### ISSUE TITLE
Compatibility with "Workspace-matrix" extension thumbnails

### ISSUE THREAD

**Issue by commadot2** [jeffshee/gnome-ext-hanabi#47]
With this extension **Workplace-matrix** function "**Show workplace thumbnails in popups**" doesn't work (all workplaces show hanabi background instead) 
I don't know is it possible at all, but it will be very useful.

**Comment by acedia73** [comment]
I also found realization of this in [Hidamari](https://github.com/jeffshee/hidamari) with option "Apply static wallpaper", it applies video frame as system wallpaper
