### ISSUE TITLE
QT5 apps context menus pop up in background behind Hanabi renderer

### ISSUE THREAD

**Issue by chinatsudori** [jeffshee/gnome-ext-hanabi#5]
QT5 apps context menus pop up in background behind Hanabi renderer window (hidden from view and appear to not be opening when clicked.)

Disabling Hanabi returns menus to normal. 

Tested with OBS-Studio, Kdenlive, RPCS3, protonup-qt ( I don't have too many QT-backed programs installed, but 4/4 seems to be a pretty good indicator that it's a conflict with QT as a whole rather than specific programs.)

**Comment by jeffshee** [comment]
Hi @chinatsudori,
Could you please provide a screenshot or even better, a screen capture? I have no idea what problem you are talking about.
I had tried Kdenlive and OBS with my system, and I didn't see anything wrong.

**Comment by jeffshee** [comment]
Closed as fixed. See issue #7
