### ISSUE TITLE
How to use hanabi on pop!_os 22.04?

### ISSUE THREAD

**Issue by azu0609** [jeffshee/gnome-ext-hanabi#51]
Hello! it's first time sending issue and I'm bad at english, so please forgive me about this.

Context:
Trying to run hanabi on pop!_os 22.04 but nothing happens when enable.
first time log says `Typelib file for namespace 'GstAudio' (any version) not found` and this can be solved by install `gir1.2-gst-plugins-base-1.0`, and after installing now it says `no property content_fit on GtkPicture` (see log on below). installed libgtk-4-media-gstreamer, codec and gstreamer related package, nothing changed.

Log:
```
Hanabi: (gjs:207826): Gtk-WARNING **: 15:51:35.828: Theme parser error: gtk.css:4715:21-28: Hash code is not a valid hex color.
Hanabi: (gjs:207826): Gtk-WARNING **: 15:51:35.828: Theme parser error: gtk.css:4731:21-29: Hash code is not a valid hex color.
Hanabi: (gjs:207826): Gtk-WARNING **: 15:51:35.839: Theme parser error: gtk.css:4715:21-28: Hash code is not a valid hex color.
Hanabi: (gjs:207826): Gtk-WARNING **: 15:51:35.839: Theme parser error: gtk.css:4731:21-29: Hash code is not a valid hex color.
[Hanabi], renderer == null, retry `_applyWallpaper()` after 100ms
[Hanabi], renderer == null, retry `_applyWallpaper()` after 100ms
[Hanabi], renderer == null, retry `_applyWallpaper()` after 100ms
[Hanabi], renderer == null, retry `_applyWallpaper()` after 100ms
Hanabi: codepath = /home/azuki/.local/share/gnome-shell/extensions/hanabi-extension@jeffshee.github.io
Hanabi: filepath = /home/azuki/Videos/Hidamari/Winter-Village.mp4
[Hanabi], renderer == null, retry `_applyWallpaper()` after 100ms
[Hanabi], renderer == null, retry `_applyWallpaper()` after 100ms
[Hanabi], renderer == null, retry `_applyWallpaper()` after 100ms
[Hanabi], renderer == null, retry `_applyWallpaper()` after 100ms
[Hanabi], renderer == null, retry `_applyWallpaper()` after 100ms
[Hanabi], renderer == null, retry `_applyWallpaper()` after 100ms
Hanabi: (gjs:207826): Gjs-CRITICAL **: 15:51:35.853: JS ERROR: Error: No property content_fit on GtkPicture
[Hanabi], renderer == null, retry `_applyWallpaper()` after 100ms
Hanabi: _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:55:50
[Hanabi], renderer == null, retry `_applyWallpaper()` after 100ms
Hanabi: _getWidgetFromSharedPaintable@/home/azuki/.local/share/gnome-shell/extensions/hanabi-extension@jeffshee.github.io/renderer/renderer.js:307:21
Hanabi: _getGtkStockWidget@/home/azuki/.local/share/gnome-shell/extensions/hanabi-extension@jeffshee.github.io/renderer/renderer.js:402:33
Hanabi: _buildUI/<@/home/azuki/.local/share/gnome-shell/extensions/hanabi-extension@jeffshee.github.io/renderer/renderer.js:287:39
Hanabi: _buildUI@/home/azuki/.local/share/gnome-shell/extensions/hanabi-extension@jeffshee.github.io/renderer/renderer.js:256:28
Hanabi: HanabiRenderer/<@/home/azuki/.local/share/gnome-shell/extensions/hanabi-extension@jeffshee.github.io/renderer/renderer.js:105:26
Hanabi: HanabiRenderer/<@/home/azuki/.local/share/gnome-shell/extensions/hanabi-extension@jeffshee.github.io/renderer/renderer.js:115:26
Hanabi: @/home/azuki/.local/share/gnome-shell/extensions/hanabi-extension@jeffshee.github.io/renderer/renderer.js:502:10
[Hanabi], renderer == null, retry `_applyWallpaper()` after 100ms
[Hanabi], renderer == null, retry `_applyWallpaper()` after 100ms
[Hanabi], renderer == null, retry `_applyWallpaper()` after 100ms
[Hanabi], renderer == null, retry `_applyWallpaper()` after 100ms
[Hanabi], renderer == null, retry `_applyWallpaper()` after 100ms
[Hanabi], renderer == null, retry `_applyWallpaper()` after 100ms
[Hanabi], renderer == null, retry `_applyWallpaper()` after 100ms
[Hanabi], renderer == null, retry `_applyWallpaper()` after 100ms
[Hanabi], renderer == null, retry `_applyWallpaper()` after 100ms
[Hanabi], renderer == null, retry `_applyWallpaper()` after 100ms
[Hanabi], renderer == null, retry `_applyWallpaper()` after 100ms
```
(pressed ctrl+c at this point because log generating forever until manually stop)
Seems like GtkPicture doesen't have content_fit property because current gtk4 version in ubuntu 22.04/pop!_os 22.04 is 4.6.6, and content_fit introduced on 4.8. so i think this can be solved by installing gtk4.8 but i don't know how to install gtk4.8... anyone can you help me please? (Hidamari works but it's buggy so i want to try out this. render test(./run.sh renderer) not working with same log but without ```[Hanabi], renderer == null, retry `_applyWallpaper()` after 100ms```).

**Comment by jeffshee** [comment]
@azu0609 Hi there~

> Seems like GtkPicture doesen't have content_fit property because current gtk4 version in ubuntu 22.04/pop!_os 22.04 is 4.6.6, and content_fit introduced on 4.8.

Yeah, it seems you need to get a newer version of GTK. But I don't think you could upgrade that easily.

> render test(./run.sh renderer) not working with same log but without [Hanabi], renderer == null, retry `_applyWallpaper()` after 100ms).

The extension depends on the renderer. If the renderer isn't working, the extension won't work as well.

I will do a hotfix to disable "Fit mode" (the feature added recently that had used the `content-fit`) when the GTK version is under 4.8 then. Otherwise, most Ubuntu-based users will encounter this issue, and that's bad. 😟

Meanwhile, you could try using an older version of Hanabi until the fix become available.
The command below should get you the version before Fit mode is implemented.
```
git clone https://github.com/jeffshee/gnome-ext-hanabi.git
cd gnome-ext-hanabi
git checkout 029f53aab3e80887445c2a6caf59c36f08cf3bda
cd src
./install.sh
```

**Comment by azu0609** [comment]
omg finally hanabi running on pop os
thanks so much!

**Comment by azu0609** [comment]
oh, i thought already installed all dependencies but `gir1.2-gst-plugins-bad-1.0` not installed. Installing this solved all problem. thank you!
