### ISSUE TITLE
Lateral workspaces are not visible

### ISSUE THREAD

**Issue by S1rPh0en1x** [jeffshee/gnome-ext-hanabi#6]
If I am not on the first or second workspace, the Lateral workspaces are hidden

https://user-images.githubusercontent.com/75997391/181389394-7665d7ae-e714-4f1d-9457-f2fa37b490f9.mp4

**Comment by jeffshee** [comment]
@S1rPh0en1x Thanks for reporting.

Yeah, I'm aware of this issue, but still haven't figured out what is wrong. I will do more research.

P/S: So the "blur my shell" extension does actually work fine with this extension, huh? I never tested it. 🤯

**Comment by jeffshee** [comment]
Hi @S1rPh0en1x 

This is also fixed in the latest master =)
