### ISSUE TITLE
Transparent top panel issue 

### ISSUE THREAD

**Issue by Clutchnp** [jeffshee/gnome-ext-hanabi#62]
On latest version of gnome when using blur my shell to make the top panel transparent instead of showing the video it instead shows the old image wallpaper in panel area

**Comment by jeffshee** [comment]
Hi @Clutchnp,
To achieve a blurred live wallpaper in your top panel, please follow these steps:
1. Go to Blur My Shell > Panel.
2. Disable the "Static blur" option.

Please be aware that currently, only the panel is compatible with Hanabi. Other features will require some architectural changes on my part. No ETA for the integration, but I will make it happen in the future. 😉

**Comment by Clutchnp** [comment]
Thank you it's working fine now and I can enjoy my panel.great work on the extension and can't wait to see further development 😃
