### ISSUE TITLE
I hear audio, but no video

### ISSUE THREAD

**Issue by lain-uses-linux** [jeffshee/gnome-ext-hanabi#75]
**Description**
When I am running the extension I hear the audio but have no video, instead only a black screen. Tested running renderer, the same thing.

**OS and Shell Information**
My system is Arch Linux with Gnome 44.3 and Wayland

**Steps to Reproduce**
Installed from github

**Additional Information**
Here is my log data:
```
Object .Gjs_ui_messageTray_Notification (0x5642c2fbb7f0), has been already disposed — impossible to emit any signal on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x5642bdaa1c80 ==
#0   5642bec79a28 i   resource:///org/gnome/shell/ui/messageTray.js:493 (13fcbed200b0 @ 69)
#1   5642bec79980 i   resource:///org/gnome/shell/ui/messageTray.js:489 (13fcbed20060 @ 56)
#2   5642bec798f8 i   resource:///org/gnome/shell/ui/calendar.js:796 (13fcbed28240 @ 22)
== Stack trace for context 0x5642bdaa1c80 ==
#0   5642bec79a28 i   resource:///org/gnome/shell/ui/messageTray.js:494 (13fcbed200b0 @ 84)
#1   5642bec79980 i   resource:///org/gnome/shell/ui/messageTray.js:489 (13fcbed20060 @ 56)
#2   5642bec798f8 i   resource:///org/gnome/shell/ui/calendar.js:796 (13fcbed28240 @ 22)
Object .Gjs_ui_messageTray_Notification (0x5642c2fbb7f0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
```

**Comment by lain-uses-linux** [comment]
I got the solution, I just used webp instead of mp4, @jeffshee fix that please, I lost so many hours on it ;(

Nevertheless, great extension!

**Comment by jeffshee** [comment]
Hi @lain-uses-linux,
I don't have any issue with mp4 at all, you might want to check for missing codecs in your system.
Nevertheless, I'm glad to hear that you had found your solution.

**Comment by Robert-Nogueira** [comment]
Hi, the same problem is happening to me, when I try to use .mp4 files only audio plays, but .webmp files work fine.
