### ISSUE TITLE
wayland sink for gstreamer

### ISSUE THREAD

**Issue by VarLad** [jeffshee/gnome-ext-hanabi#79]
Hey! I just saw the waylandsink https://gstreamer.freedesktop.org/documentation/waylandsink/index.html 
Wondering if this can work for default fallback on wayland (when clappersink is not available)

**Comment by jeffshee** [comment]
Hi @VarLad, thanks for suggesting. But it doesn't look promising to me, as it lacks the ability to control window's properties, such as title, height, width, etc. Also, the currently implemented logic based on `GdkPaintable` was working so fine, and the `waylandsink` is a completely different approach that would involve extra efforts and experiments.

> when clappersink is not available

This could be solved by packaging in the future.
