### ISSUE TITLE
The extension is incompatible with the current GNOME version

### ISSUE THREAD

**Issue by MonadWizard** [jeffshee/gnome-ext-hanabi#95]
**Description**
Please describe your feature request here.

**OS and Shell Information**
Please provide your OS name
 - OS: [e.g. Fedora 39]

**Additional Information**
SyntaxError: import declarations may only appear at top level of a module

Stack trace:
  @file:///home/monad/.local/share/gnome-shell/extensions/hanabi-extension@jeffshee.github.io/prefs.js:23:24
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

**Comment by jeffshee** [comment]
Hi @MonadWizard 

You are probably using the current `master` branch, which the port for GNOME 45 hasn't been merged yet.
Please use the `gnome-45` branch for GNOME 45 for now.
That means when you do the git clone, you will need to specify the branch like this:
```
git clone https://github.com/jeffshee/gnome-ext-hanabi.git -b gnome-45
```
I'll update the installation guide for GNOME 45 when I have free time.
